name: Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  markdown-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: markdown-link-check
        uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
